name: Publish

on:
  workflow_dispatch

env:
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
  CLOUDSMITH_PASSWORD: ${{ secrets.CLOUDSMITH_PASSWORD }}


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: publish
        run: ./gradlew publish

      - name: modrinth
        run: ./gradlew modrinth

      - name: curseforge
        run: ./gradlew curseforge

